.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resources :comments
  end

  root "welcome#index"
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  
  validates :title,
    presence: true,
    length: { minimum: 5 }
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :text))
      redirect_to action: :show, id: @post.id
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:title, :text))

    if @post.save
      redirect_to action: :show, id: @post.id
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to action: :index
  end
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/helpers/application_helper.rb
module ApplicationHelper
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/helpers/comments_helper.rb
module CommentsHelper
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/helpers/posts_helper.rb
module PostsHelper
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/helpers/welcome_helper.rb
module WelcomeHelper
end

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', action: :index %>

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', action: :show, id: post.id %></td>
    <td><%= link_to 'Edit', action: :edit, id: post.id %></td>
    <td><%= link_to 'Destroy', { action: :destroy, id: post.id },
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/posts/new.html.erb
<h1>New post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', action: :index %>

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

.rvm/gems/ruby-2.0.0-p247/gems/rails-4.0.0/guides/code/getting_started/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to "My Blog", controller: "posts" %>